import { Brain, Shield, Zap, AlertTriangle, CheckCircle, Info } from 'lucide-react';
import type { AnalysisResult } from '../services/codeAnalysisService';

interface AnalysisResultsProps {
  result: AnalysisResult;
}

export function AnalysisResults({ result }: AnalysisResultsProps) {
  const getProbabilityColor = (probability: number) => {
    if (probability >= 70) return 'text-red-600';
    if (probability >= 40) return 'text-yellow-600';
    return 'text-green-600';
  };

  const getProbabilityBg = (probability: number) => {
    if (probability >= 70) return 'bg-red-100';
    if (probability >= 40) return 'bg-yellow-100';
    return 'bg-green-100';
  };

  const getSeverityColor = (severity: string) => {
    switch (severity) {
      case 'high':
        return 'bg-red-100 text-red-700';
      case 'medium':
        return 'bg-yellow-100 text-yellow-700';
      default:
        return 'bg-blue-100 text-blue-700';
    }
  };

  const getPriorityIcon = (priority: string) => {
    switch (priority) {
      case 'high':
        return <AlertTriangle className="w-4 h-4 text-red-600" />;
      case 'medium':
        return <Info className="w-4 h-4 text-yellow-600" />;
      default:
        return <CheckCircle className="w-4 h-4 text-blue-600" />;
    }
  };

  return (
    <div className="space-y-6">
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center space-x-3">
            <div className="bg-blue-100 p-2 rounded-lg">
              <Brain className="w-6 h-6 text-blue-600" />
            </div>
            <h2 className="text-xl font-bold text-gray-900">
              Detection Results
            </h2>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="bg-gradient-to-br from-gray-50 to-gray-100 rounded-xl p-6">
            <div className="flex items-center justify-between mb-2">
              <span className="text-sm font-medium text-gray-600">
                AI Probability
              </span>
              <span className={`text-3xl font-bold ${getProbabilityColor(result.aiProbability)}`}>
                {result.aiProbability.toFixed(1)}%
              </span>
            </div>
            <div className="w-full bg-gray-200 rounded-full h-3 overflow-hidden">
              <div
                className={`h-full ${getProbabilityBg(result.aiProbability).replace('bg-', 'bg-gradient-to-r from-')}`}
                style={{ width: `${result.aiProbability}%` }}
              />
            </div>
            <p className="text-xs text-gray-500 mt-2">
              Likelihood that this code was generated by AI
            </p>
          </div>

          <div className="bg-gradient-to-br from-gray-50 to-gray-100 rounded-xl p-6">
            <div className="flex items-center justify-between mb-2">
              <span className="text-sm font-medium text-gray-600">
                Confidence Score
              </span>
              <span className="text-3xl font-bold text-blue-600">
                {result.confidenceScore.toFixed(1)}%
              </span>
            </div>
            <div className="w-full bg-gray-200 rounded-full h-3 overflow-hidden">
              <div
                className="h-full bg-gradient-to-r from-blue-400 to-blue-600"
                style={{ width: `${result.confidenceScore}%` }}
              />
            </div>
            <p className="text-xs text-gray-500 mt-2">
              Confidence in the detection analysis
            </p>
          </div>
        </div>
      </div>

      {result.patterns.length > 0 && (
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
          <div className="flex items-center space-x-3 mb-4">
            <div className="bg-orange-100 p-2 rounded-lg">
              <Shield className="w-5 h-5 text-orange-600" />
            </div>
            <h3 className="text-lg font-bold text-gray-900">
              Detected Patterns
            </h3>
            <span className="bg-orange-100 text-orange-700 text-xs font-medium px-2.5 py-0.5 rounded-full">
              {result.patterns.length}
            </span>
          </div>

          <div className="space-y-3">
            {result.patterns.map((pattern, index) => (
              <div
                key={index}
                className="border border-gray-200 rounded-lg p-4 hover:border-gray-300 transition-colors"
              >
                <div className="flex items-start justify-between">
                  <div className="flex-1">
                    <div className="flex items-center space-x-2 mb-1">
                      <h4 className="font-semibold text-gray-900">
                        {pattern.name}
                      </h4>
                      <span className={`text-xs font-medium px-2 py-1 rounded ${getSeverityColor(pattern.severity)}`}>
                        {pattern.severity}
                      </span>
                    </div>
                    <p className="text-sm text-gray-600">
                      {pattern.description}
                    </p>
                    <p className="text-xs text-gray-500 mt-1">
                      Type: {pattern.type}
                    </p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {result.suggestions.length > 0 && (
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
          <div className="flex items-center space-x-3 mb-4">
            <div className="bg-green-100 p-2 rounded-lg">
              <Zap className="w-5 h-5 text-green-600" />
            </div>
            <h3 className="text-lg font-bold text-gray-900">
              Developer Suggestions
            </h3>
            <span className="bg-green-100 text-green-700 text-xs font-medium px-2.5 py-0.5 rounded-full">
              {result.suggestions.length}
            </span>
          </div>

          <div className="space-y-3">
            {result.suggestions.map((suggestion, index) => (
              <div
                key={index}
                className="border border-gray-200 rounded-lg p-4 hover:border-gray-300 transition-colors"
              >
                <div className="flex items-start space-x-3">
                  <div className="mt-0.5">
                    {getPriorityIcon(suggestion.priority)}
                  </div>
                  <div className="flex-1">
                    <div className="flex items-center space-x-2 mb-1">
                      <h4 className="font-semibold text-gray-900">
                        {suggestion.title}
                      </h4>
                      <span className="text-xs font-medium text-gray-500 px-2 py-0.5 bg-gray-100 rounded">
                        {suggestion.type}
                      </span>
                    </div>
                    <p className="text-sm text-gray-600">
                      {suggestion.description}
                    </p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
